[platformio]
default_envs = esp32c3_supermini

[env:esp32c3_supermini]
platform = espressif32@6.12.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -Desp_cpu_get_cycle_count=esp_cpu_get_ccount
lib_deps =
  https://github.com/Mystfit/ESP32-BLE-CompositeHID.git#06d93eab499181afaa3e26f96ecee67233c01303

[env:native]
platform = native
test_framework = unity
test_build_src = no
build_flags = -std=gnu++17
